
   CREATE SEQUENCE  SHOP2_BOOK_SEQ;
   CREATE SEQUENCE  SHOP2_CART_SEQ;
   CREATE SEQUENCE  SHOP2_HISTORY_SEQ;
   CREATE SEQUENCE  SHOP2_ORDER_ITEM_SEQ;
   CREATE SEQUENCE  SHOP2_ORDER_SEQ;
   CREATE SEQUENCE  SHOP2_REVIEW_SEQ;
   CREATE SEQUENCE  SHOP2_USER_SEQ;


  CREATE TABLE "SHOP2_BOOK_CATEGORIES" 
   (	"CATEGORY_NO" NUMBER(3,0) CONSTRAINT CATERORIES2_CATEGORYNO_PK PRIMARY KEY, 
	"CATEGORY_NAME" VARCHAR2(100) NOT NULL
   ) ;
   
 
  CREATE TABLE "SHOP2_BOOKS" 
   (	"BOOK_NO" NUMBER(7,0) CONSTRAINT BOOKS2_BOOKNO_PK PRIMARY KEY, 
	"CATEGORY_NO" NUMBER(3,0) NOT NULL CONSTRAINT BOOKS2_CATEGORYNO_FK REFERENCES SHOP2_BOOK_CATEGORIES (CATEGORY_NO), 
	"BOOK_TITLE" VARCHAR2(300) NOT NULL, 
	"BOOK_WRITER" VARCHAR2(300) NOT NULL, 
	"BOOK_TRANSLATOR" VARCHAR2(300), 
	"BOOK_PUBLISHER" VARCHAR2(300) NOT NULL, 
	"BOOK_PUB_DATE" DATE, 
	"BOOK_STOCK" NUMBER(7,0) DEFAULT 1000, 
	"BOOK_STATUS" VARCHAR2(100) DEFAULT '재고있음', 
	"BOOK_PRICE" NUMBER(7,0), 
	"BOOK_SALE_PRICE" NUMBER(7,0), 
	"BOOK_DISCOUNT_RATE" NUMBER(3,2) DEFAULT 0.1, 
	"BOOK_SAVE_POINT" NUMBER(7,0), 
	"BOOK_REVIEW_POINT" NUMBER(3,1) DEFAULT 0, 
	"BOOK_REVIEW_COUNT" NUMBER(7,0) DEFAULT 0, 
    "BOOK_BESTSELLER" CHAR(1) DEFAULT 'N',
    "BOOK_FREE_DELIVERY" CHAR(1) DEFAULT 'N',
    "BOOK_CREATED_DATE" DATE DEFAULT SYSDATE
   ) ;

  
  CREATE TABLE "SHOP2_USERS" 
   (	"USER_NO" NUMBER(7,0) CONSTRAINT USERS2_USERNO_PK PRIMARY KEY, 
	"USER_NAME" VARCHAR2(100) NOT NULL, 
	"USER_ID" VARCHAR2(12) NOT NULL CONSTRAINT USERS2_USERID_UK UNIQUE, 
	"USER_PASSWORD" CHAR(64) NOT NULL, 
	"USER_TEL" VARCHAR2(20) NOT NULL, 
	"USER_EMAIL" VARCHAR2(200) NOT NULL, 
	"USER_AVAILABLE_POINT" NUMBER(7,0) DEFAULT 0, 
	"USER_STATUS" CHAR(1) DEFAULT 'Y', 
	"USER_CREATED_DATE" DATE DEFAULT SYSDATE
   ) ;

  CREATE TABLE "SHOP2_BOOK_CART_ITEMS" 
   (	"CART_ITEM_NO" NUMBER(7,0) CONSTRAINT CARTS2_CARTITEMNO_PK PRIMARY KEY, 
	"BOOK_NO" NUMBER(7,0) NOT NULL CONSTRAINT CARTS2_BOOKNO_FK REFERENCES SHOP2_BOOKS (BOOK_NO) , 
	"USER_NO" NUMBER(7,0) NOT NULL CONSTRAINT CARTS2_USERNO_FK REFERENCES SHOP2_USERS (USER_NO), 
	"CART_ITEM_AMOUNT" NUMBER(7,0), 
	"CART_ITEM_CREATED_DATE" DATE DEFAULT SYSDATE
   ) ;
  
  CREATE TABLE "SHOP2_BOOK_REVIEWS" 
   (	"REVIEW_NO" NUMBER(7,0) CONSTRAINT REVIEWS2_REVIEWNO_PK PRIMARY KEY, 
	"BOOK_NO" NUMBER(7,0) NOT NULL CONSTRAINT REVIEWS2_BOOKNO_FK REFERENCES SHOP2_BOOKS (BOOK_NO), 
	"USER_NO" NUMBER(7,0) NOT NULL CONSTRAINT REVIEWS2_USERNO_FK REFERENCES SHOP2_USERS (USER_NO),  
	"REVIEW_TITLE" VARCHAR2(250) NOT NULL, 
	"REVIEW_CONTENT" VARCHAR2(1000) NOT NULL, 
	"REVIEW_BOOK_POINT" NUMBER(2,0) NOT NULL, 
	"REVIEW_LIKE_COUNT" NUMBER(7,0) DEFAULT 0, 
	"REVIEW_CREATED_DATE" DATE DEFAULT SYSDATE
   ) ;   
   
  CREATE TABLE "SHOP2_BOOK_REVIEW_LIKE_USERS" 
   (	"REVIEW_NO" NUMBER(7,0) NOT NULL CONSTRAINT REVIEWLIKES2_REVIEWNO_FK REFERENCES SHOP2_BOOK_REVIEWS (REVIEW_NO), 
	"USER_NO" NUMBER(7,0) NOT NULL CONSTRAINT REVIEWLIKES2_USERNO_FK REFERENCES SHOP2_USERS (USER_NO),
    CONSTRAINT REVIEWLIKES2_UK UNIQUE (REVIEW_NO, USER_NO)
   ) ;
   
  
  CREATE TABLE "SHOP2_BOOK_ORDERS" 
   (	"ORDER_NO" NUMBER(7,0) CONSTRAINT ORDERS2_ORDERNO_PK PRIMARY KEY, 
	"USER_NO" NUMBER(7,0) NOT NULL CONSTRAINT ORDERS2_USERNO_FK REFERENCES SHOP2_USERS (USER_NO), 
    "ORDER_DESCRIPTION" VARCHAR2(250) NOT NULL,
	"ORDER_AMOUNT" NUMBER(7,0), 
	"ORDER_STATUS" VARCHAR2(100) DEFAULT '결재완료', 
	"ORDER_RECIPIENT_NAME" VARCHAR2(100) NOT NULL, 
	"ORDER_RECIPIENT_TEL" VARCHAR2(20) NOT NULL, 
	"ORDER_RECIPIENT_ZIPCODE" CHAR(5) NOT NULL, 
	"ORDER_RECIPIENT_ADDRESS" VARCHAR2(200) NOT NULL, 
	"ORDER_MESSAGE" VARCHAR2(500), 
	"TOTAL_ORDER_PRICE" NUMBER(7,0) NOT NULL, 
	"USED_POINT_AMOUNT" NUMBER(7,0) DEFAULT 0, 
	"TOTAL_PAYMENT_PRICE" NUMBER(7,0) NOT NULL, 
    "TOTAL_SAVED_POINT" NUMBER(7,0) NOT NULL,
	"ORDER_CREATED_DATE" DATE DEFAULT SYSDATE
   ) ;
   
  CREATE TABLE "SHOP2_BOOK_ORDER_ITEMS" 
   (	"ORDER_ITEM_NO" NUMBER(7,0) CONSTRAINT ORDERTEMS2_ITEMNO_PK PRIMARY KEY, 
	"ORDER_NO" NUMBER(7,0) NOT NULL CONSTRAINT  ORDERITEMS2_ORDERNO_FK REFERENCES SHOP2_BOOK_ORDERS (ORDER_NO), 
	"BOOK_NO" NUMBER(7,0) NOT NULL CONSTRAINT ORDERITEMS2_BOOKNO_FK REFERENCES SHOP2_BOOKS (BOOK_NO), 
	"ITEM_PRICE" NUMBER(7,0) NOT NULL, 
	"ORDER_ITEM_AMOUNT" NUMBER(7,0)
   ) ;


  CREATE TABLE "SHOP2_USER_POINT_HISTORIES" 
   (	"HISTORY_NO" NUMBER(7,0) CONSTRAINT POINTHISTORY2_HISTORYNO_PK PRIMARY KEY, 
	"USER_NO" NUMBER(7,0) NOT NULL CONSTRAINT POINTHISTORY2_USERNO_FK REFERENCES SHOP2_USERS (USER_NO), 
	"HISTORY_CONTENT" VARCHAR2(200), 
	"ORDER_NO" NUMBER(7,0) CONSTRAINT POINTHISTORY2_ORDERNO_FK REFERENCES SHOP2_BOOK_ORDERS (ORDER_NO), 
	"HISTORY_POINT_AMOUNT" NUMBER(7,0), 
	"HISTORY_CREATED_DATE" DATE DEFAULT SYSDATE
   ) ;
   
Insert into SHOP2_BOOK_CATEGORIES (CATEGORY_NO,CATEGORY_NAME) values (100,'국내도서');
Insert into SHOP2_BOOK_CATEGORIES (CATEGORY_NO,CATEGORY_NAME) values (200,'외국도서');
Insert into SHOP2_BOOK_CATEGORIES (CATEGORY_NO,CATEGORY_NAME) values (300,'전자책');

Insert into SHOP2_BOOKS (BOOK_NO,CATEGORY_NO,BOOK_TITLE,BOOK_WRITER,BOOK_TRANSLATOR,BOOK_PUBLISHER,BOOK_PUB_DATE,BOOK_STOCK,BOOK_STATUS,BOOK_PRICE,BOOK_SALE_PRICE,BOOK_DISCOUNT_RATE,BOOK_SAVE_POINT,BOOK_REVIEW_POINT,BOOK_REVIEW_COUNT,BOOK_CREATED_DATE,BOOK_BESTSELLER) values (1000001,100,'달러구트 꿈 백화점','이미예',null,'팩토리라인',to_date('20/07/08','RR/MM/DD'),10000,'재고있음',13800,12420,0.1,690,0,0,to_date('21/01/04','RR/MM/DD'),'N');
Insert into SHOP2_BOOKS (BOOK_NO,CATEGORY_NO,BOOK_TITLE,BOOK_WRITER,BOOK_TRANSLATOR,BOOK_PUBLISHER,BOOK_PUB_DATE,BOOK_STOCK,BOOK_STATUS,BOOK_PRICE,BOOK_SALE_PRICE,BOOK_DISCOUNT_RATE,BOOK_SAVE_POINT,BOOK_REVIEW_POINT,BOOK_REVIEW_COUNT,BOOK_CREATED_DATE,BOOK_BESTSELLER) values (1000002,100,'트렌드 코리아 2021','김난도, 전미영, 최지혜, 이향은, 이준영',null,'미래의창',to_date('20/10/14','RR/MM/DD'),10000,'재고있음',18000,16200,0.1,900,0,0,to_date('21/01/04','RR/MM/DD'),'N');
Insert into SHOP2_BOOKS (BOOK_NO,CATEGORY_NO,BOOK_TITLE,BOOK_WRITER,BOOK_TRANSLATOR,BOOK_PUBLISHER,BOOK_PUB_DATE,BOOK_STOCK,BOOK_STATUS,BOOK_PRICE,BOOK_SALE_PRICE,BOOK_DISCOUNT_RATE,BOOK_SAVE_POINT,BOOK_REVIEW_POINT,BOOK_REVIEW_COUNT,BOOK_CREATED_DATE,BOOK_BESTSELLER) values (1000003,100,'어떻게 만해줘야 할까','오은영',null,'김영사',to_date('20/10/25','RR/MM/DD'),10000,'재고있음',17500,15750,0.1,870,0,0,to_date('21/01/04','RR/MM/DD'),'Y');
Insert into SHOP2_BOOKS (BOOK_NO,CATEGORY_NO,BOOK_TITLE,BOOK_WRITER,BOOK_TRANSLATOR,BOOK_PUBLISHER,BOOK_PUB_DATE,BOOK_STOCK,BOOK_STATUS,BOOK_PRICE,BOOK_SALE_PRICE,BOOK_DISCOUNT_RATE,BOOK_SAVE_POINT,BOOK_REVIEW_POINT,BOOK_REVIEW_COUNT,BOOK_CREATED_DATE,BOOK_BESTSELLER) values (1000004,100,'공정하다는 착각','마이클 샌덜','함규진','와이즈베리',to_date('20/12/10','RR/MM/DD'),10000,'재고있음',18000,16200,0.1,900,0,0,to_date('21/01/04','RR/MM/DD'),'N');
Insert into SHOP2_BOOKS (BOOK_NO,CATEGORY_NO,BOOK_TITLE,BOOK_WRITER,BOOK_TRANSLATOR,BOOK_PUBLISHER,BOOK_PUB_DATE,BOOK_STOCK,BOOK_STATUS,BOOK_PRICE,BOOK_SALE_PRICE,BOOK_DISCOUNT_RATE,BOOK_SAVE_POINT,BOOK_REVIEW_POINT,BOOK_REVIEW_COUNT,BOOK_CREATED_DATE,BOOK_BESTSELLER) values (1000005,100,'미스터 마켓 2021','이한영, 김효진, 염승환, 이효석, 이다솔',null,'페이지2',to_date('20/11/11','RR/MM/DD'),10000,'재고있음',17000,15300,0.1,850,0,0,to_date('21/01/04','RR/MM/DD'),'N');
Insert into SHOP2_BOOKS (BOOK_NO,CATEGORY_NO,BOOK_TITLE,BOOK_WRITER,BOOK_TRANSLATOR,BOOK_PUBLISHER,BOOK_PUB_DATE,BOOK_STOCK,BOOK_STATUS,BOOK_PRICE,BOOK_SALE_PRICE,BOOK_DISCOUNT_RATE,BOOK_SAVE_POINT,BOOK_REVIEW_POINT,BOOK_REVIEW_COUNT,BOOK_CREATED_DATE,BOOK_BESTSELLER) values (1000006,100,'해커스 토익 기출 보카','데이비드 조',null,'해커스어학연구소',to_date('19/01/20','RR/MM/DD'),10000,'재고있음',12900,11610,0.1,640,0,0,to_date('21/01/04','RR/MM/DD'),'Y');
Insert into SHOP2_BOOKS (BOOK_NO,CATEGORY_NO,BOOK_TITLE,BOOK_WRITER,BOOK_TRANSLATOR,BOOK_PUBLISHER,BOOK_PUB_DATE,BOOK_STOCK,BOOK_STATUS,BOOK_PRICE,BOOK_SALE_PRICE,BOOK_DISCOUNT_RATE,BOOK_SAVE_POINT,BOOK_REVIEW_POINT,BOOK_REVIEW_COUNT,BOOK_CREATED_DATE,BOOK_BESTSELLER) values (1000007,100,'나의 하루는 4시 30분에 시작된다','김유진',null,'토네이도',to_date('20/10/15','RR/MM/DD'),10000,'재고있음',15000,13500,0.1,750,0,0,to_date('21/01/04','RR/MM/DD'),'N');
Insert into SHOP2_BOOKS (BOOK_NO,CATEGORY_NO,BOOK_TITLE,BOOK_WRITER,BOOK_TRANSLATOR,BOOK_PUBLISHER,BOOK_PUB_DATE,BOOK_STOCK,BOOK_STATUS,BOOK_PRICE,BOOK_SALE_PRICE,BOOK_DISCOUNT_RATE,BOOK_SAVE_POINT,BOOK_REVIEW_POINT,BOOK_REVIEW_COUNT,BOOK_CREATED_DATE,BOOK_BESTSELLER) values (1000008,100,'마음챙김의 시','류시화',null,'수오서재',to_date('20/09/10','RR/MM/DD'),10000,'재고있음',13000,11700,0.1,650,0,0,to_date('21/01/04','RR/MM/DD'),'N');
Insert into SHOP2_BOOKS (BOOK_NO,CATEGORY_NO,BOOK_TITLE,BOOK_WRITER,BOOK_TRANSLATOR,BOOK_PUBLISHER,BOOK_PUB_DATE,BOOK_STOCK,BOOK_STATUS,BOOK_PRICE,BOOK_SALE_PRICE,BOOK_DISCOUNT_RATE,BOOK_SAVE_POINT,BOOK_REVIEW_POINT,BOOK_REVIEW_COUNT,BOOK_CREATED_DATE,BOOK_BESTSELLER) values (1000009,100,'주식투자 무작정 따라하기','윤재수',null,'길벗',to_date('20/01/05','RR/MM/DD'),10000,'재고있음',18000,16200,0.1,900,0,0,to_date('21/01/04','RR/MM/DD'),'N');
Insert into SHOP2_BOOKS (BOOK_NO,CATEGORY_NO,BOOK_TITLE,BOOK_WRITER,BOOK_TRANSLATOR,BOOK_PUBLISHER,BOOK_PUB_DATE,BOOK_STOCK,BOOK_STATUS,BOOK_PRICE,BOOK_SALE_PRICE,BOOK_DISCOUNT_RATE,BOOK_SAVE_POINT,BOOK_REVIEW_POINT,BOOK_REVIEW_COUNT,BOOK_CREATED_DATE,BOOK_BESTSELLER) values (1000010,100,'이토록 공부가 재미있어지는 순간','박성혁',null,'다산북스',to_date('20/07/10','RR/MM/DD'),10000,'재고있음',15000,13500,0.1,750,0,0,to_date('21/01/04','RR/MM/DD'),'N');
Insert into SHOP2_BOOKS (BOOK_NO,CATEGORY_NO,BOOK_TITLE,BOOK_WRITER,BOOK_TRANSLATOR,BOOK_PUBLISHER,BOOK_PUB_DATE,BOOK_STOCK,BOOK_STATUS,BOOK_PRICE,BOOK_SALE_PRICE,BOOK_DISCOUNT_RATE,BOOK_SAVE_POINT,BOOK_REVIEW_POINT,BOOK_REVIEW_COUNT,BOOK_CREATED_DATE,BOOK_BESTSELLER) values (1000011,200,'Smart Phonics 1','편집부',null,'이퓨처',to_date('10/10/11','RR/MM/DD'),10000,'재고있음',13000,11700,0.1,590,0,0,to_date('21/01/04','RR/MM/DD'),'Y');
Insert into SHOP2_BOOKS (BOOK_NO,CATEGORY_NO,BOOK_TITLE,BOOK_WRITER,BOOK_TRANSLATOR,BOOK_PUBLISHER,BOOK_PUB_DATE,BOOK_STOCK,BOOK_STATUS,BOOK_PRICE,BOOK_SALE_PRICE,BOOK_DISCOUNT_RATE,BOOK_SAVE_POINT,BOOK_REVIEW_POINT,BOOK_REVIEW_COUNT,BOOK_CREATED_DATE,BOOK_BESTSELLER) values (1000012,200,'Wonder','RJ Palacio',null,'Random House',to_date('14/06/30','RR/MM/DD'),10000,'재고있음',11900,7200,0.3,0,0,0,to_date('21/01/04','RR/MM/DD'),'N');
Insert into SHOP2_BOOKS (BOOK_NO,CATEGORY_NO,BOOK_TITLE,BOOK_WRITER,BOOK_TRANSLATOR,BOOK_PUBLISHER,BOOK_PUB_DATE,BOOK_STOCK,BOOK_STATUS,BOOK_PRICE,BOOK_SALE_PRICE,BOOK_DISCOUNT_RATE,BOOK_SAVE_POINT,BOOK_REVIEW_POINT,BOOK_REVIEW_COUNT,BOOK_CREATED_DATE,BOOK_BESTSELLER) values (1000013,200,'Smart phonics 2','편집부',null,'이퓨처',to_date('10/10/11','RR/MM/DD'),10000,'재고있음',13000,11700,0.1,590,0,0,to_date('21/01/04','RR/MM/DD'),'N');
Insert into SHOP2_BOOKS (BOOK_NO,CATEGORY_NO,BOOK_TITLE,BOOK_WRITER,BOOK_TRANSLATOR,BOOK_PUBLISHER,BOOK_PUB_DATE,BOOK_STOCK,BOOK_STATUS,BOOK_PRICE,BOOK_SALE_PRICE,BOOK_DISCOUNT_RATE,BOOK_SAVE_POINT,BOOK_REVIEW_POINT,BOOK_REVIEW_COUNT,BOOK_CREATED_DATE,BOOK_BESTSELLER) values (1000014,200,'The Giver','로이스 로리',null,'Houghton Mifflin Harcourt',to_date('14/07/15','RR/MM/DD'),10000,'재고있음',10800,5500,0.4,0,0,0,to_date('21/01/04','RR/MM/DD'),'N');
Insert into SHOP2_BOOKS (BOOK_NO,CATEGORY_NO,BOOK_TITLE,BOOK_WRITER,BOOK_TRANSLATOR,BOOK_PUBLISHER,BOOK_PUB_DATE,BOOK_STOCK,BOOK_STATUS,BOOK_PRICE,BOOK_SALE_PRICE,BOOK_DISCOUNT_RATE,BOOK_SAVE_POINT,BOOK_REVIEW_POINT,BOOK_REVIEW_COUNT,BOOK_CREATED_DATE,BOOK_BESTSELLER) values (1000015,200,'English for Everyday Activities','Lawrence J. Zwier',null,'Compass Publishing',to_date('11/02/01','RR/MM/DD'),10000,'재고있음',12000,10200,0.15,0,0,0,to_date('21/01/04','RR/MM/DD'),'Y');
Insert into SHOP2_BOOKS (BOOK_NO,CATEGORY_NO,BOOK_TITLE,BOOK_WRITER,BOOK_TRANSLATOR,BOOK_PUBLISHER,BOOK_PUB_DATE,BOOK_STOCK,BOOK_STATUS,BOOK_PRICE,BOOK_SALE_PRICE,BOOK_DISCOUNT_RATE,BOOK_SAVE_POINT,BOOK_REVIEW_POINT,BOOK_REVIEW_COUNT,BOOK_CREATED_DATE,BOOK_BESTSELLER) values (1000016,200,'Holes','루이스 쌔커',null,'Yearling Books',to_date('00/05/10','RR/MM/DD'),10000,'재고있음',10700,5900,0.45,0,0,0,to_date('21/01/04','RR/MM/DD'),'N');
Insert into SHOP2_BOOKS (BOOK_NO,CATEGORY_NO,BOOK_TITLE,BOOK_WRITER,BOOK_TRANSLATOR,BOOK_PUBLISHER,BOOK_PUB_DATE,BOOK_STOCK,BOOK_STATUS,BOOK_PRICE,BOOK_SALE_PRICE,BOOK_DISCOUNT_RATE,BOOK_SAVE_POINT,BOOK_REVIEW_POINT,BOOK_REVIEW_COUNT,BOOK_CREATED_DATE,BOOK_BESTSELLER) values (1000017,200,'13 Reasons Why','Jay Asher',null,'Razorbill',to_date('17/03/20','RR/MM/DD'),10000,'재고있음',13100,10480,0.2,530,0,0,to_date('21/01/04','RR/MM/DD'),'N');
Insert into SHOP2_BOOKS (BOOK_NO,CATEGORY_NO,BOOK_TITLE,BOOK_WRITER,BOOK_TRANSLATOR,BOOK_PUBLISHER,BOOK_PUB_DATE,BOOK_STOCK,BOOK_STATUS,BOOK_PRICE,BOOK_SALE_PRICE,BOOK_DISCOUNT_RATE,BOOK_SAVE_POINT,BOOK_REVIEW_POINT,BOOK_REVIEW_COUNT,BOOK_CREATED_DATE,BOOK_BESTSELLER) values (1000018,200,'Smart Phonics 5','편집부',null,'이퓨처',to_date('10/10/11','RR/MM/DD'),10000,'재고있음',13000,11700,0.1,590,0,0,to_date('21/01/04','RR/MM/DD'),'N');
Insert into SHOP2_BOOKS (BOOK_NO,CATEGORY_NO,BOOK_TITLE,BOOK_WRITER,BOOK_TRANSLATOR,BOOK_PUBLISHER,BOOK_PUB_DATE,BOOK_STOCK,BOOK_STATUS,BOOK_PRICE,BOOK_SALE_PRICE,BOOK_DISCOUNT_RATE,BOOK_SAVE_POINT,BOOK_REVIEW_POINT,BOOK_REVIEW_COUNT,BOOK_CREATED_DATE,BOOK_BESTSELLER) values (1000019,200,'Smart Phonics 3','편집부',null,'이퓨처',to_date('10/10/11','RR/MM/DD'),10000,'재고있음',13000,11700,0.1,590,0,0,to_date('21/01/04','RR/MM/DD'),'N');
Insert into SHOP2_BOOKS (BOOK_NO,CATEGORY_NO,BOOK_TITLE,BOOK_WRITER,BOOK_TRANSLATOR,BOOK_PUBLISHER,BOOK_PUB_DATE,BOOK_STOCK,BOOK_STATUS,BOOK_PRICE,BOOK_SALE_PRICE,BOOK_DISCOUNT_RATE,BOOK_SAVE_POINT,BOOK_REVIEW_POINT,BOOK_REVIEW_COUNT,BOOK_CREATED_DATE,BOOK_BESTSELLER) values (1000020,200,'Smart Phonics 4','편집부',null,'이퓨처',to_date('10/10/11','RR/MM/DD'),10000,'재고있음',13000,11700,0.1,590,0,0,to_date('21/01/04','RR/MM/DD'),'Y');
Insert into SHOP2_BOOKS (BOOK_NO,CATEGORY_NO,BOOK_TITLE,BOOK_WRITER,BOOK_TRANSLATOR,BOOK_PUBLISHER,BOOK_PUB_DATE,BOOK_STOCK,BOOK_STATUS,BOOK_PRICE,BOOK_SALE_PRICE,BOOK_DISCOUNT_RATE,BOOK_SAVE_POINT,BOOK_REVIEW_POINT,BOOK_REVIEW_COUNT,BOOK_CREATED_DATE,BOOK_BESTSELLER) values (1000021,300,'한순간에','수잰 레드펀','김마림','열린책들',to_date('20/12/25','RR/MM/DD'),0,'재고있음',10500,10500,0,320,0,0,to_date('21/01/04','RR/MM/DD'),'N');
Insert into SHOP2_BOOKS (BOOK_NO,CATEGORY_NO,BOOK_TITLE,BOOK_WRITER,BOOK_TRANSLATOR,BOOK_PUBLISHER,BOOK_PUB_DATE,BOOK_STOCK,BOOK_STATUS,BOOK_PRICE,BOOK_SALE_PRICE,BOOK_DISCOUNT_RATE,BOOK_SAVE_POINT,BOOK_REVIEW_POINT,BOOK_REVIEW_COUNT,BOOK_CREATED_DATE,BOOK_BESTSELLER) values (1000022,300,'청소부 매뉴얼','루시아 벌리','공진호','웅진지식하우스',to_date('20/12/28','RR/MM/DD'),0,'재고있음',11200,11200,0,340,0,0,to_date('21/01/04','RR/MM/DD'),'N');
Insert into SHOP2_BOOKS (BOOK_NO,CATEGORY_NO,BOOK_TITLE,BOOK_WRITER,BOOK_TRANSLATOR,BOOK_PUBLISHER,BOOK_PUB_DATE,BOOK_STOCK,BOOK_STATUS,BOOK_PRICE,BOOK_SALE_PRICE,BOOK_DISCOUNT_RATE,BOOK_SAVE_POINT,BOOK_REVIEW_POINT,BOOK_REVIEW_COUNT,BOOK_CREATED_DATE,BOOK_BESTSELLER) values (1000023,300,'미드나잇 선','스테프니 메이어','신연희','북폴리오',to_date('21/01/04','RR/MM/DD'),0,'재고있음',11000,9900,0.1,550,0,0,to_date('21/01/04','RR/MM/DD'),'N');
Insert into SHOP2_BOOKS (BOOK_NO,CATEGORY_NO,BOOK_TITLE,BOOK_WRITER,BOOK_TRANSLATOR,BOOK_PUBLISHER,BOOK_PUB_DATE,BOOK_STOCK,BOOK_STATUS,BOOK_PRICE,BOOK_SALE_PRICE,BOOK_DISCOUNT_RATE,BOOK_SAVE_POINT,BOOK_REVIEW_POINT,BOOK_REVIEW_COUNT,BOOK_CREATED_DATE,BOOK_BESTSELLER) values (1000024,300,'부의 대이동','오건영',null,'페이지2',to_date('20/07/12','RR/MM/DD'),0,'재고있음',12000,12000,0,600,0,0,to_date('21/01/04','RR/MM/DD'),'N');
Insert into SHOP2_BOOKS (BOOK_NO,CATEGORY_NO,BOOK_TITLE,BOOK_WRITER,BOOK_TRANSLATOR,BOOK_PUBLISHER,BOOK_PUB_DATE,BOOK_STOCK,BOOK_STATUS,BOOK_PRICE,BOOK_SALE_PRICE,BOOK_DISCOUNT_RATE,BOOK_SAVE_POINT,BOOK_REVIEW_POINT,BOOK_REVIEW_COUNT,BOOK_CREATED_DATE,BOOK_BESTSELLER) values (1000025,300,'뉴욕주민의 진짜 미국식 주식투자','뉴욕주민',null,'비즈니스 북스',to_date('20/12/26','RR/MM/DD'),0,'재고있음',16100,144490,0.1,810,0,0,to_date('21/01/04','RR/MM/DD'),'N');
Insert into SHOP2_BOOKS (BOOK_NO,CATEGORY_NO,BOOK_TITLE,BOOK_WRITER,BOOK_TRANSLATOR,BOOK_PUBLISHER,BOOK_PUB_DATE,BOOK_STOCK,BOOK_STATUS,BOOK_PRICE,BOOK_SALE_PRICE,BOOK_DISCOUNT_RATE,BOOK_SAVE_POINT,BOOK_REVIEW_POINT,BOOK_REVIEW_COUNT,BOOK_CREATED_DATE,BOOK_BESTSELLER) values (1000026,300,'아몬드','손원평',null,'창비',to_date('17/03/10','RR/MM/DD'),0,'재고있음',8400,8400,0,420,0,0,to_date('21/01/04','RR/MM/DD'),'N');
Insert into SHOP2_BOOKS (BOOK_NO,CATEGORY_NO,BOOK_TITLE,BOOK_WRITER,BOOK_TRANSLATOR,BOOK_PUBLISHER,BOOK_PUB_DATE,BOOK_STOCK,BOOK_STATUS,BOOK_PRICE,BOOK_SALE_PRICE,BOOK_DISCOUNT_RATE,BOOK_SAVE_POINT,BOOK_REVIEW_POINT,BOOK_REVIEW_COUNT,BOOK_CREATED_DATE,BOOK_BESTSELLER) values (1000027,300,'시선으로부터','정세랑',null,'문학동네',to_date('20/07/30','RR/MM/DD'),0,'재고있음',9800,9800,0,490,0,0,to_date('21/01/04','RR/MM/DD'),'N');
Insert into SHOP2_BOOKS (BOOK_NO,CATEGORY_NO,BOOK_TITLE,BOOK_WRITER,BOOK_TRANSLATOR,BOOK_PUBLISHER,BOOK_PUB_DATE,BOOK_STOCK,BOOK_STATUS,BOOK_PRICE,BOOK_SALE_PRICE,BOOK_DISCOUNT_RATE,BOOK_SAVE_POINT,BOOK_REVIEW_POINT,BOOK_REVIEW_COUNT,BOOK_CREATED_DATE,BOOK_BESTSELLER) values (1000028,300,'자기 결정','파스칼 메르시어',null,'은행나무',to_date('15/11/20','RR/MM/DD'),0,'재고있음',6000,6000,0,300,0,0,to_date('21/01/04','RR/MM/DD'),'Y');
Insert into SHOP2_BOOKS (BOOK_NO,CATEGORY_NO,BOOK_TITLE,BOOK_WRITER,BOOK_TRANSLATOR,BOOK_PUBLISHER,BOOK_PUB_DATE,BOOK_STOCK,BOOK_STATUS,BOOK_PRICE,BOOK_SALE_PRICE,BOOK_DISCOUNT_RATE,BOOK_SAVE_POINT,BOOK_REVIEW_POINT,BOOK_REVIEW_COUNT,BOOK_CREATED_DATE,BOOK_BESTSELLER) values (1000029,300,'위기의 시대, 돈의 미래','짐 로저스','전경아','리더스북',to_date('20/11/05','RR/MM/DD'),0,'재고있음',12300,12300,0,620,0,0,to_date('21/01/04','RR/MM/DD'),'N');
Insert into SHOP2_BOOKS (BOOK_NO,CATEGORY_NO,BOOK_TITLE,BOOK_WRITER,BOOK_TRANSLATOR,BOOK_PUBLISHER,BOOK_PUB_DATE,BOOK_STOCK,BOOK_STATUS,BOOK_PRICE,BOOK_SALE_PRICE,BOOK_DISCOUNT_RATE,BOOK_SAVE_POINT,BOOK_REVIEW_POINT,BOOK_REVIEW_COUNT,BOOK_CREATED_DATE,BOOK_BESTSELLER) values (1000030,300,'주린이도 술술 읽는 친절한 주식책','이슬기, 최정의',null,'메이트북스',to_date('20/09/20','RR/MM/DD'),0,'재고있음',9000,9000,0,450,0,0,to_date('21/01/04','RR/MM/DD'),'N');

Insert into SHOP2_USERS (USER_NO,USER_NAME,USER_ID,USER_PASSWORD,USER_TEL,USER_EMAIL,USER_AVAILABLE_POINT,USER_STATUS,USER_CREATED_DATE) values (1000000,'홍길동','hong','bef9bc5fb772c39fb335768e85bb188470130a65fe1ee92463827127b4d0670f','010-1111-1111','hong@abc.net',0,'Y',to_date('21/01/04','RR/MM/DD'));


COMMIT;
